# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/melange/refs/heads/main/pkg/config/schema.json

package:
  name: bootc
  version: 1.5.1
  epoch: 0
  description: Boot and upgrade via container images
  copyright:
    - license: Apache-2.0-only

environment:
  contents:
    packages:
      - busybox
      - build-base
      - cargo-auditable
      - rust
      - zstd-dev
      - openssl-dev
      - glib-dev
      - ostree-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bootc-dev/bootc.git
      branch: composefs-backend
      # tag: v${{ package.version }}
      expected-commit: 04f048f855fe64352af8bdf9c7eab87b123e3a9a

  - runs: |
      cargo auditable build --release --locked
      install -Dm755 -t ${{targets.destdir}}/usr/bin target/release/bootc
      install -Dm755 -t ${{targets.destdir}}/usr/bin target/release/system-reinstall-bootc

  - uses: strip
