# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/melange/refs/heads/main/pkg/config/schema.json

package:
  name: bootupd
  version: 0.2.27
  epoch: 1
  description: Bootloader updater
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - build-base
      - wolfi-baselayout
      - cargo-auditable
      - autoconf
      - automake
      - rust
      - systemd
      - openssl-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/coreos/bootupd
      tag: v${{package.version}}
      expected-commit: 3203db5800e4e261bb1d04bf58c578eadf13da73

  - runs: |
      cargo auditable build --release --locked

  - runs: |
      make install INSTALL="install -p -c" DESTDIR=${{targets.destdir}}
      make install-grub-static DESTDIR=${{targets.destdir}}
