package:
  name: bootc
  version: 1.5.1
  epoch: 0
  description: Boot and upgrade via container images
  copyright:
    - license: Apache-2.0-only

environment:
  contents:
    packages:
      - ostree-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bootc-dev/bootc.git
      tag: v${{package.version}}
      expected-commit: 3a0c6abd9bc79f07302b27bf66f63c3943e7a6c8

  - uses: cargo/build
    with:
      output: bootc

  - uses: strip
