package:
  name: bootupd
  version: 0.2.28
  epoch: 2
  description: Bootloader updater
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - openssl-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/coreos/bootupd
      tag: v${{package.version}}
      expected-commit: 766bb80cbe22bcaba3f4c466385bf38d089f2917

  - uses: cargo/build
    with:
      output: bootupd

  - uses: autoconf/make-install

  - uses: autoconf/make
    with:
      opts: install-grub-static DESTDIR="${{targets.destdir}}"

  - uses: strip

test:
  pipeline:
    - runs: |
        set -o pipefail
        bootupd --help | grep -F -e "Bootupd backend commands"
        bootupd --version | grep -F -e "${{package.version}}"
        bootupctl --help | grep -F -e "Bootupd client application"
        bootupctl --version | grep -F -e "${{package.version}}"

update:
  enabled: true
  github:
    identifier: coreos/bootupd
    strip-prefix: v
