package:
  name: bootc
  version: 1.5.1
  epoch: 0
  description: Boot and upgrade via container images
  copyright:
    - license: Apache-2.0-only

environment:
  contents:
    packages:
      - ostree-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bootc-dev/bootc.git
      branch: composefs-backend
      expected-commit: 04f048f855fe64352af8bdf9c7eab87b123e3a9a

  - uses: cargo/build
    with:
      output: bootc

  - uses: strip

test:
  environment:
    contents:
      packages:
        - yq
  pipeline:
    - runs: |
        set -o pipefail
        bootc --version | grep -F -e "${{package.version}}"
        bootc --help | grep -F -e "Deploy and transactionally in-place with bootable container images."
        bootc status | yq .apiVersion | grep -F -e "org.containers.bootc/v1"

update:
  enabled: true
  github:
    identifier: bootc-dev/bootc
    strip-prefix: v
