package:
  name: kernel-uki
  version: 6.15.6
  epoch: 1
  description: Unified Kernel Image (UKI) for the Linux kernel
  target-architecture:
    - x86_64
  copyright:
    - license: GPL-2.0

environment:
  contents:
    packages:
      - busybox
      - build-base
      - binutils-dev
      - wolfi-baselayout
      - kernel-core
      - kernel-modules
      - systemd-ukify
      - systemd-uki-tools
      - python3
      - py3-pefile
      - dracut
      - kmod
      - zstd
      - posix-libc-utils

pipeline:
  - runs: |
      mkdir -p /var/tmp
      depmod ${{package.version}}
      dracut --force --no-hostonly --reproducible --zstd --verbose --kver ${{package.version}} /usr/lib/modules/${{package.version}}/initramfs.img

  - runs: |
      ukify build \
        --linux=/usr/lib/${{package.version}}/vmlinuz \
        --initrd=/usr/lib/modules/${{package.version}}/initramfs.img
