# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/melange/refs/heads/main/pkg/config/schema.json

package:
  name: kernel-initramfs
  version: 6.15.6
  epoch: 1
  description: The Linux kernel initramfs
  copyright:
    - license: GPL-2.0
  dependencies:
    runtime:
      - kernel-core
      - kernel-modules
      - zstd

environment:
  contents:
    packages:
      - attr
      - bash
      - busybox
      - binutils-dev
      - btrfs-progs
      - build-base
      - composefs-rs
      - coreutils
      - cryptsetup
      - device-mapper
      - dracut
      # For modules
      - kernel-core
      - kernel-modules
      - kmod
      - lvm2
      - openssl
      - posix-libc-utils
      - systemd
      - udev
      - util-linux
      - wolfi-baselayout
      - zstd

pipeline:
  - runs: |
      mkdir -p /var/tmp ${{targets.destdir}}/usr/lib/modules/${{package.version}}
      depmod ${{package.version}}
      dracut --force --no-hostonly --reproducible --zstd --verbose \
        --kver ${{package.version}} --omit busybox \
        ${{targets.destdir}}/usr/lib/modules/${{package.version}}/initramfs.img


test:
  pipeline:
    - name: Check if initramfs exists with right permissions
      runs: |
        stat ${{targets.destdir}}/usr/lib/modules/${{package.version}}/initramfs.img | grep -F -e "0644"

update:
  enabled: false
