# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/melange/refs/heads/main/pkg/config/schema.json

package:
  name: kernel-uki
  version: 6.15.6
  epoch: 1
  description: Unified Kernel Image (UKI) for the Linux kernel
  target-architecture:
    - x86_64
  copyright:
    - license: GPL-2.0
  dependencies:
    runtime:
      - bootupd

environment:
  contents:
    packages:
      - busybox
      - build-base
      - binutils-dev
      - wolfi-baselayout
      - kernel
      - kernel-modules
      - kernel-initramfs
      - systemd-ukify
      - systemd-uki-tools
      - systemd-measure
      - python3
      - dracut
      - kmod
      - zstd
      - posix-libc-utils

pipeline:
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/modules/${{package.version}}
      ukify build \
        --measure \
        --linux=/usr/lib/modules/${{package.version}}/vmlinuz \
        --initrd=/usr/lib/modules/${{package.version}}/initramfs.img \
        --output=${{targets.destdir}}/usr/lib/modules/${{package.version}}/uki.efi
